#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GROUPS_DIR="${GROUPS_DIR:-$ROOT_DIR/groups}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-$ROOT_DIR/artifacts/r7-drill}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
WORK_DIR="$ARTIFACT_ROOT/$TIMESTAMP"
BASELINE_DIR="$WORK_DIR/baseline"
MUTATED_DIR="$WORK_DIR/mutated"
RECOVERED_DIR="$WORK_DIR/recovered"
BACKUP_FILE="$WORK_DIR/backup.tar.gz"
REPORT_FILE="$WORK_DIR/report.txt"
RPO_TARGET_SECONDS="${RPO_TARGET_SECONDS:-900}"
RTO_TARGET_SECONDS="${RTO_TARGET_SECONDS:-1800}"

mkdir -p "$GROUPS_DIR" "$BASELINE_DIR" "$MUTATED_DIR" "$RECOVERED_DIR" "$WORK_DIR"

cp -R "$GROUPS_DIR"/. "$BASELINE_DIR" 2>/dev/null || true
cp -R "$GROUPS_DIR"/. "$MUTATED_DIR" 2>/dev/null || true

CANARY_FILE="$MUTATED_DIR/.r7_drill_canary"
BACKUP_EPOCH="$(date +%s)"
echo "backup_at=$BACKUP_EPOCH" > "$CANARY_FILE"

tar -czf "$BACKUP_FILE" -C "$BASELINE_DIR" .

sleep 2
MUTATION_EPOCH="$(date +%s)"
echo "mutated_at=$MUTATION_EPOCH" >> "$CANARY_FILE"

RESTORE_START_EPOCH="$(date +%s)"
tar -xzf "$BACKUP_FILE" -C "$RECOVERED_DIR"
RESTORE_END_EPOCH="$(date +%s)"

RPO_SECONDS=$((MUTATION_EPOCH - BACKUP_EPOCH))
RTO_SECONDS=$((RESTORE_END_EPOCH - RESTORE_START_EPOCH))

RPO_RESULT="PASS"
if [ "$RPO_SECONDS" -gt "$RPO_TARGET_SECONDS" ]; then
  RPO_RESULT="FAIL"
fi

RTO_RESULT="PASS"
if [ "$RTO_SECONDS" -gt "$RTO_TARGET_SECONDS" ]; then
  RTO_RESULT="FAIL"
fi

OVERALL_RESULT="PASS"
if [ "$RPO_RESULT" = "FAIL" ] || [ "$RTO_RESULT" = "FAIL" ]; then
  OVERALL_RESULT="FAIL"
fi

cat > "$REPORT_FILE" <<EOF
R7_BACKUP_RESTORE_DRILL_RESULT=$OVERALL_RESULT
TIMESTAMP=$TIMESTAMP
GROUPS_DIR=$GROUPS_DIR
BACKUP_FILE=$BACKUP_FILE
RPO_SECONDS=$RPO_SECONDS
RPO_TARGET_SECONDS=$RPO_TARGET_SECONDS
RPO_RESULT=$RPO_RESULT
RTO_SECONDS=$RTO_SECONDS
RTO_TARGET_SECONDS=$RTO_TARGET_SECONDS
RTO_RESULT=$RTO_RESULT
WORK_DIR=$WORK_DIR
EOF

cat "$REPORT_FILE"

if [ "$OVERALL_RESULT" = "FAIL" ]; then
  exit 1
fi
